[package]
name = "mytemplate"
version = "0.1.0"
edition = "2021"
authors = ["ChimeWu<wujicheng0215@outlook.com>"]
license = "MIT"

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
tokio = "1.38.0"
tokio-tungstenite = "0.23.1"
tracing = "0.1.40"
